uiopen('*_visual.mat');
s1 = s;
stim1 = stim;
m1 = m;
uiopen('*_visual.mat');
s2 = s;
stim2 = stim;
m2 = m;
stim.loopEndIdx = [stim1.loopEndIdx stim2.loopEndIdx(2:end)+stim1.loopEndIdx(end)];
stim.stimLength = [stim1.stimLength stim2.stimLength];
stim.stimLength = [stim1.stimLength stim2.stimLength];